@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

CardiBuddy *-right-> "1" UniqueDeckList
CardiBuddy *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueDeckList
UniqueTagList -[hidden]down- UniqueDeckList

UniqueTagList *-right-> "*" Tag
UniqueDeckList o-right-> Deck

Deck o-up-> "*" Tag

Deck *--> Name
Deck *--> Phone
Deck *--> Email
Deck *--> Address
@enduml
