@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyCardiBuddy <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class CardiBuddy
Class ReadOnlyCardiBuddy
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Deck {
Class Deck
Class Title
Class UniqueDeckList
}

Package Flashcards {
Class Flashcard
Class Question
Class Answer
Class UniqueFlashcardList
}

Package Tag {
Class Tag
}

Package TestSession {
Class TestSession
Class TestResult
Enum Result <<Enum>>
Enum AnswerType <<Enum>>
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

CardiBuddy .up.|> ReadOnlyCardiBuddy


Model .right.> ObservableList
ModelManager .up.|> Model
ModelManager o-right-> "1" CardiBuddy
ModelManager o--> "1" UserPrefs
ModelManager -->"1" Deck : filtered list
ModelManager o---> "1" TestSession : > manages
UserPrefs .up.|> ReadOnlyUserPrefs


CardiBuddy *--> "1" UniqueDeckList
UniqueDeckList o--> "*" Deck
Deck *--> Title
Deck *--> "*" Flashcard
Deck *--> "*" Tag

TestSession --> "1" Deck
TestSession *--> "1..*" TestResult


TestResult o-> "1" Answer
Flashcard o-right-> Question
Flashcard o-left-> Answer



@enduml
