@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":SearchCommandParser" as SearchCommandParser LOGIC_COLOR
participant "sc:SearchCommand" as SearchCommand LOGIC_COLOR
participant "sdkp:SearchDeckKeywordsPredicate" as SearchDeckKeywordsPredicate LOGIC_COLOR
participant "cr:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR

end box

[-> SearchCommandParser: parseCommand(search ...)
activate SearchCommandParser

create SearchDeckKeywordsPredicate
SearchCommandParser -> SearchDeckKeywordsPredicate: nameKeywords
activate SearchDeckKeywordsPredicate
SearchDeckKeywordsPredicate --> SearchCommandParser: sdkp
deactivate SearchDeckKeywordsPredicate

create SearchCommand
SearchCommandParser -> SearchCommand: SearchCommand(sdkp)
SearchCommandParser -> SearchCommand: parse(arguments)

activate SearchCommand

SearchCommand --> SearchCommandParser: sc
deactivate SearchCommand

[<-- SearchCommandParser: sc
deactivate SearchCommandParser

[-> SearchCommand: execute()
activate SearchCommand

SearchCommand -> Model: updateFilteredDeckList(predicate)
activate Model

Model --> SearchCommand: filteredList: ObservableList<Deck>
deactivate Model

SearchCommand -> Model: getFilteredDeckList().size()
activate Model
Model --> SearchCommand: size
deactivate Model

create CommandResult
SearchCommand -> CommandResult: size

activate CommandResult
CommandResult --> SearchCommand: cr
deactivate CommandResult

[<-- SearchCommand: cr
deactivate SearchCommand

@enduml
