@startuml
:CardiBuddy: as Admin

(start test session) as (Start)
(submit answer) as (Submit)
(exception thrown) as (Exception)

skinparam packageStyle rectangle

actor CardiBuddy
actor User

rectangle start {
note top of (Start): CardiBuddy displays the first question to the user
User -> (Start)
CardiBuddy -> (Start)
}



@enduml