= Ashleigh - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: AddressBook - Level 3

---

== Overview

AddressBook - Level 3 is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *the ability to start a test session with a selected deck of flashcards.k*
** What it does: allows the user to test themselves on their subject content by:
*** 1. Fetching the flashcards of the deck at the user's specified index and displaying them question by question.
*** 2. Adding flashcards back into the test session if they got it wrong **(prioritisation)**
*** 3. Checking the user's answer with the flashcard's stored answer, and showing them the outcome (Right or Wrong).
*** 4. Storing the test results (Number of tries, correct/wrong) to generate statistics for the user to view at the end of each test.
*** 5. Giving users the ability to force correct answers if their answers differ from the flashcard's stored answer.
*** 6. Giving users the ability to skip questions when needed.
*** 7. Giving users the ability to quit the ongoing test session halfway.
** Justification: This feature improves the product significantly as a flashcard application can not be without a testing feature. In addition, this feature provides certain enhancements on top of basic testing - such as prioritisation, skipping and the ability to force correct answers. This provides greater flexibility in how the user chooses to answer questions, and allows for paraphrasing of answers which improves information retention.

** Highlights: This enhancement is a major overhaul to the application, and required an in-depth analysis of design alternatives. The implementation was challenging as it required deep analysis of the application in order to figure out how to replace the existing JavaFX scene with the test session. In addition, the test session required tight integration with other aspects of the application such as Flashcards and Decks, and constant communication and clarification with the team was required.

* *Minor enhancement*: added a history command that allows the user to navigate to previous commands using up/down keys.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=delete]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
