= Qiu Jing Ying - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== Overview

*CardiBuddy (CardiB)* is a flash cards application that allows students to generate their own flash cards and test
themselves through a simple Command Line Interface. It is specially designed for SoC students as a desktop
application as they are generally comfortable with typing.

== Summary of contributions

* *Major enhancement*: added *the ability to insert images into flashcards*
** What it does: allows the user to add images from their local drive into flashcards.
** Justification: This feature improves the product significantly because users are able to include images such as
diagrams to illustrate more complex concepts (such as UML diagrams for CS2103).
** Highlights: This enhancement affects the Model and Logic section of Cardi Buddy.
It required an in-depth analysis of design alternatives.
The implementation too was challenging as it required changes to existing commands such as the add command and the
creation of a new type of object (Imagecard object). In addition, changes were made to the UI in the FlashcardListPanel
to display images in the flashcard.

* *Minor enhancement*: added a filter command that allows the user to filter decks via tags and an and-or feature to the filter and search command.

* *Minor enhancement*: created three different answer types to questions in flashcards (T/F, MCQ and Short Answer) to make testing easier.

* *Minor enhancement*: added an insert image button that shows a popup window for the user to choose the .png and .jpg
files they want to insert into their flashcards so that they do not have to key in their filepath.

* *Code contributed*: [https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=t10&sort=groupTitle&sortWithin=title&since=2020-02-14&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=haveaqiupill&tabRepo=AY1920S2-CS2103T-T10-2%2Fmain%5Bmaster%5D[Functional code]][https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=t10&sort=groupTitle&sortWithin=title&since=2020-02-14&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=haveaqiupill&tabRepo=AY1920S2-CS2103T-T10-2%2Fmain%5Bmaster%5D[Test code]]

* *Other contributions*:

** Project management:
*** Morphed entire code base from AB3 to Cardi Buddy https://github.com/AY1920S2-CS2103T-T10-2/main/pull/84[#84], https://github.com/AY1920S2-CS2103T-T10-2/main/pull/85[#85], https://github.com/AY1920S2-CS2103T-T10-2/main/pull/96[#96]
*** Managed releases `v1.3.1` (1 release) on GitHub for the product to be tested in the Mock Practical Examination

** Enhancements to existing features:
*** Re-designed UI (Pull requests https://github.com/AY1920S2-CS2103T-T10-2/main/pull/114[#114],
https://github.com/AY1920S2-CS2103T-T10-2/main/pull/199[#199])
*** Improved on existing find command (renamed to search command) with an and-or function that allows the user to search for
decks and cards that contains all of the keywords instead of any of the keywords.
*** Refactored commands from AB3 such as AddCommand to AddDeckCommand, AddFlashcardCommand and AddImageCardCommand as well as the DeleteCommand to DeleteCardCommand and DeleteDeckCommand.
*** Wrote additional tests for the classes in Deck, Tag and Flashcard folders to increase coverage from 13% to 27%
(Pull requests https://github.com/AY1920S2-CS2103T-T10-2/main/pull/200[#200])


** Documentation:
*** Did content and cosmetic tweaks to existing contents of the User Guide: https://github.com/AY1920S2-CS2103T-T10-2/main/pull/206[#206], https://github.com/AY1920S2-CS2103T-T10-2/main/pull/211[#211]
*** Wrote the whole README, AboutUs and designed the Ui Mock-up: https://github.com/AY1920S2-CS2103T-T10-2/main/pull/54[#54], https://github.com/AY1920S2-CS2103T-T10-2/main/pull/57[#57]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/AY1920S2-CS2103T-T10-2/main/pull/119[#119]
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com/nus-cs2103-AY1920S2/addressbook-level3/pull/41[1], https://github.com/nus-cs2103-AY1920S2/addressbook-level3/pull/5[2])
** Tools:
*** Integrated automated hosting platform (Netlify) to the project (https://github.com/AY1920S2-CS2103T-T10-2/main/pull/60[#60])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=addingImage]

include::../UserGuide.adoc[tag=search]

include::../UserGuide.adoc[tag=filter]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=jingying]

|===
|_Given below is a design consideration that I’ve included in the Developer Guide for a feature implemented._
|===

include::../DeveloperGuide.adoc[tag=design]

---
